name: publish
on:
  push:
    branches:
      - main
  schedule:
    - cron: '20 4 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Read version
        run: echo "TS3_VERSION=$(echo "$(cat Dockerfile | grep "VERSION=")" | sed -E 's/.*=//g')" >> $GITHUB_ENV
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ts3:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ts3:${{ env.TS3_VERSION }}
