name: publish

on:
  push:
    branches:
      - main
      - master
  schedule:
    - cron: '20 4 * * *'

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ts3:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ts3:3.13.6
