name: ci
on:
  push:
    branches:
      - main
  schedule:
    - cron: '20 4 * * *'
jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      - name: 'Checkout repo'
        uses: actions/checkout@v4

      - name: 'Find TS3 version'
        run: echo "TS3_VERSION=$(echo "$(cat Dockerfile | grep "VERSION=")" | sed -E 's/.*=//g' | tr -d '"')" >> $GITHUB_ENV

      - name: 'Docker Hub login'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: 'Build and publish image'
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/ts3:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/ts3:${{ env.TS3_VERSION }}

      - name: 'Trigger deployment'
        run: >
          curl
          --fail
          --head
          --no-progress-meter
          --header "Authorization: Bearer ${{ secrets.WATCHTOWER_TOKEN }}"
          "${{ secrets.WATCHTOWER_URL }}"
